### ISSUE TITLE
[CHANGE REQUEST] Adding new WTO changes numbering

### ISSUE THREAD

**Issue by thegreenalien** [1V-Oct/3318_the_centre_releases#30]
When you add a new WTO, it's numbered WTO01. However, when you add a second WTO, it gets numbered WTO01 and the previous one becomes WTO02.

**Comment by duddie** [comment]
That is as designed. They are numbered in order they appear. So if you add before existing one then the existing will get number increased. When you delete they all get renumbered. But the links in inputs and outputs remain unchanged and linked to proper module (at the time of assignment).

**Comment by duddie** [comment]
This only happens if you add modules in front of other modules. If you add at the end (scroll after your first WTO and add, it does not renumber. If there is general need to do so, I will reework it. But I really would like to documented first with all cases: what happens if I delete WTO? Should it renumber or should the others keep the numbers? And there is more questions like that. Currently they are always numbered in the order they are in list and they will not get renumbered if you keep adding modules AFTER the current module.
